[package]
name = "blog_os"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "=0.9.22"
volatile = "=0.2.6"
spin = "0.5.2"


[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]